/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pitcer_janot_gtk_NativeContainer */

#ifndef _Included_pl_pitcer_janot_gtk_NativeContainer
#define _Included_pl_pitcer_janot_gtk_NativeContainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pitcer_janot_gtk_NativeContainer
 * Method:    setBorderWidth
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeContainer_setBorderWidth
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     pl_pitcer_janot_gtk_NativeContainer
 * Method:    add
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeContainer_add
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
