/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pitcer_janot_gtk_NativeWidget */

#ifndef _Included_pl_pitcer_janot_gtk_NativeWidget
#define _Included_pl_pitcer_janot_gtk_NativeWidget
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pitcer_janot_gtk_NativeWidget
 * Method:    showAll
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeWidget_showAll
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
