/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pitcer_janot_gtk_NativeGtk */

#ifndef _Included_pl_pitcer_janot_gtk_NativeGtk
#define _Included_pl_pitcer_janot_gtk_NativeGtk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pitcer_janot_gtk_NativeGtk
 * Method:    init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeGtk_init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     pl_pitcer_janot_gtk_NativeGtk
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeGtk_main
  (JNIEnv *, jclass);

/*
 * Class:     pl_pitcer_janot_gtk_NativeGtk
 * Method:    mainQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeGtk_mainQuit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
