/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pitcer_janot_Janot */

#ifndef _Included_pl_pitcer_janot_Janot
#define _Included_pl_pitcer_janot_Janot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pitcer_janot_Janot
 * Method:    helloJanot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_Janot_helloJanot
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
