/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pitcer_janot_gtk_NativeWindow */

#ifndef _Included_pl_pitcer_janot_gtk_NativeWindow
#define _Included_pl_pitcer_janot_gtk_NativeWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pitcer_janot_gtk_NativeWindow
 * Method:    newInstance
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_pl_pitcer_janot_gtk_NativeWindow_newInstance
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
