/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pitcer_janot_gtk_NativeButton */

#ifndef _Included_pl_pitcer_janot_gtk_NativeButton
#define _Included_pl_pitcer_janot_gtk_NativeButton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pitcer_janot_gtk_NativeButton
 * Method:    newInstance
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_pl_pitcer_janot_gtk_NativeButton_newInstance
  (JNIEnv *, jclass);

/*
 * Class:     pl_pitcer_janot_gtk_NativeButton
 * Method:    setLabel
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeButton_setLabel
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     pl_pitcer_janot_gtk_NativeButton
 * Method:    setClickedCallback
 * Signature: (Ljava/nio/ByteBuffer;Lpl/pitcer/janot/gtk/ClickedCallback;)V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_gtk_NativeButton_setClickedCallback
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
