/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pitcer_janot_notify_NativeNotify */

#ifndef _Included_pl_pitcer_janot_notify_NativeNotify
#define _Included_pl_pitcer_janot_notify_NativeNotify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pitcer_janot_notify_NativeNotify
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_pl_pitcer_janot_notify_NativeNotify_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pl_pitcer_janot_notify_NativeNotify
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_notify_NativeNotify_uninit
  (JNIEnv *, jclass);

/*
 * Class:     pl_pitcer_janot_notify_NativeNotify
 * Method:    isInitted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_pl_pitcer_janot_notify_NativeNotify_isInitted
  (JNIEnv *, jclass);

/*
 * Class:     pl_pitcer_janot_notify_NativeNotify
 * Method:    getAppName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pl_pitcer_janot_notify_NativeNotify_getAppName
  (JNIEnv *, jclass);

/*
 * Class:     pl_pitcer_janot_notify_NativeNotify
 * Method:    setAppName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pl_pitcer_janot_notify_NativeNotify_setAppName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
